### ISSUE TITLE
Improve default ETCD configuration

### ISSUE THREAD

**Issue by tuxtof** [nutanix-cloud-native/cluster-api-runtime-extensions-nutanix#806]
there is few change we can apply to the default etcd config to:
- fix CVE issue rise by Nesus scanner
- improve Kubernetes STIG posture

goal is to inject inside kubeadmcontrolplane object in spec.kubeadmConfigSpec. clusterConfiguration.etcd

the following entry

```
  etcd:
    local:
      extraArgs:
        auto-tls: "false"
        peer-auto-tls: "false"
        cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"
```
